name: Build the IG
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: fhir-ig
      - run: git reset --hard origin/fhir-ig
      - uses: qligier/fhir-ig-action@v0.3.0
        with:
          ig-publisher: "latest"
          sushi: "latest"
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f /home/runner/work/bghd-ig/bghd-ig/output
          git commit -m "output generated"
          git push
