name: Build the IG
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: qligier/fhir-ig-action@v0.3.0
        with:
          ig-publisher: "latest"
          sushi: "latest"
